{{- if .Values.geoDB.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: geodl
  namespace: echo2
data:
  entryscript.sh: |-
    #!/bin/sh
    set -e

    apk add --no-interactive -q curl tar
    
    # ASN
    cd /geodata
    curl -OJL -u $GEOAUTH 'https://download.maxmind.com/geoip/databases/GeoLite2-ASN/download?suffix=tar.gz'
    curl -OJL -u $GEOAUTH 'https://download.maxmind.com/geoip/databases/GeoLite2-ASN/download?suffix=tar.gz.sha256'
    sha256sum -s -c *.sha256
    rm -f *.sha256

    # City  
    curl -OJL -u $GEOAUTH 'https://download.maxmind.com/geoip/databases/GeoLite2-City/download?suffix=tar.gz'
    curl -OJL -u $GEOAUTH 'https://download.maxmind.com/geoip/databases/GeoLite2-City/download?suffix=tar.gz.sha256'
    sha256sum -s -c *.sha256
    rm -f *.sha256
    
    # Country
    curl -OJL -u $GEOAUTH 'https://download.maxmind.com/geoip/databases/GeoLite2-Country/download?suffix=tar.gz'
    curl -OJL -u $GEOAUTH 'https://download.maxmind.com/geoip/databases/GeoLite2-Country/download?suffix=tar.gz.sha256'
    sha256sum -s -c *.sha256
    rm -f *.sha256

    find . -maxdepth 1 -type f -iname "*.tar.gz" -exec tar -x --wildcards "*.mmdb" --strip-components=1 -f '{}' \;

    rm *.tar.gz
{{- end }}