---
apiVersion: apps/v1
kind: Deployment
metadata:
 namespace: {{ .Values.namespace }}
 name: {{ .Release.Name }}-deployment
 labels:
   app: echoip
spec:
 replicas: 1
 selector:
   matchLabels:
     app: echoip
 template:
   metadata:
     labels:
       app: echoip
   spec:
     containers:
     - name: echo
       image: {{ .Values.container.image }}:{{ .Values.container.tag }}
       ports:
       - containerPort: 8080
       args: {{ toYaml .Values.container.commandargs | nindent 8 }}
